import { sql } from 'drizzle-orm'
import { boolean, index, pgTable, text, timestamp, uuid } from 'drizzle-orm/pg-core'

/**
 * Better Auth's tables, generated by `npx @better-auth/cli generate` and then
 * edited only where this repo needs a column of its own (see `blockedAt`).
 *
 * Kept in its own module rather than merged into `schema.ts` so that the split
 * between "generated, regenerate when the auth config changes" and "written by
 * hand" stays visible. `db.ts` merges the two into the one schema object Drizzle
 * wants; the FK direction is one-way, ledger -> user, so there is no cycle.
 *
 * Two things here are not the generator's defaults and must survive a
 * regeneration:
 *
 *  - **ids are uuid**, because `owner_id` on nine ledger tables references
 *    `user.id` and Postgres will not join text to uuid. This comes from
 *    `advanced.database.generateId: 'uuid'` in the auth config; with the pg
 *    Drizzle adapter Better Auth then omits the id and lets the column default
 *    fire, which is why every id carries `gen_random_uuid()`.
 *  - the table is named **`user`**, a reserved word in Postgres. Every
 *    hand-written statement touching it must quote it as `"user"`.
 *
 * The generator also emits `relations(...)` helpers. They are dropped: nothing
 * in this repo uses Drizzle's relational query builder, and unused exports read
 * as an API someone is meant to call.
 */

export const user = pgTable('user', {
  id: uuid('id').default(sql`pg_catalog.gen_random_uuid()`).primaryKey(),
  name: text('name').notNull(),
  email: text('email').notNull().unique(),
  emailVerified: boolean('email_verified').default(false).notNull(),
  image: text('image'),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at')
    .defaultNow()
    .$onUpdate(() => new Date())
    .notNull(),
  /**
   * Supplied by the anonymous plugin. Read by the 24-hour reaper and by quota
   * selection, so it lives on `user` rather than in a parallel table: both are
   * wanted on every authenticated request and a join for one boolean is pure
   * overhead.
   */
  isAnonymous: boolean('is_anonymous').default(false),
  /**
   * Set by the operator action in spec §9.4. Not generated by the CLI — this is
   * kakeibo's column, and it is here for the same reason `is_anonymous` is.
   */
  blockedAt: timestamp('blocked_at', { withTimezone: true }),
})

export const session = pgTable(
  'session',
  {
    id: uuid('id').default(sql`pg_catalog.gen_random_uuid()`).primaryKey(),
    expiresAt: timestamp('expires_at').notNull(),
    token: text('token').notNull().unique(),
    createdAt: timestamp('created_at').defaultNow().notNull(),
    updatedAt: timestamp('updated_at')
      .$onUpdate(() => new Date())
      .notNull(),
    ipAddress: text('ip_address'),
    userAgent: text('user_agent'),
    userId: uuid('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
  },
  (table) => [index('session_userId_idx').on(table.userId)],
)

export const account = pgTable(
  'account',
  {
    id: uuid('id').default(sql`pg_catalog.gen_random_uuid()`).primaryKey(),
    accountId: text('account_id').notNull(),
    providerId: text('provider_id').notNull(),
    userId: uuid('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    accessToken: text('access_token'),
    refreshToken: text('refresh_token'),
    idToken: text('id_token'),
    accessTokenExpiresAt: timestamp('access_token_expires_at'),
    refreshTokenExpiresAt: timestamp('refresh_token_expires_at'),
    scope: text('scope'),
    password: text('password'),
    createdAt: timestamp('created_at').defaultNow().notNull(),
    updatedAt: timestamp('updated_at')
      .$onUpdate(() => new Date())
      .notNull(),
  },
  (table) => [index('account_userId_idx').on(table.userId)],
)

export const verification = pgTable(
  'verification',
  {
    id: uuid('id').default(sql`pg_catalog.gen_random_uuid()`).primaryKey(),
    identifier: text('identifier').notNull(),
    value: text('value').notNull(),
    expiresAt: timestamp('expires_at').notNull(),
    createdAt: timestamp('created_at').defaultNow().notNull(),
    updatedAt: timestamp('updated_at')
      .defaultNow()
      .$onUpdate(() => new Date())
      .notNull(),
  },
  (table) => [index('verification_identifier_idx').on(table.identifier)],
)

export type User = typeof user.$inferSelect
export type Session = typeof session.$inferSelect
